name: flutter_sentry
description: Sentry.io error reporting plugin for Flutter, offering tight integration with Flutter and native code.
version: 0.0.2
homepage: https://github.com/dasfoo/flutter_sentry

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  sentry: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package:  org.dasfoo.flutter_sentry
        pluginClass: FlutterSentryPlugin
      ios:
        pluginClass: FlutterSentryPlugin
